admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /admin

messenger:
    resource: "@MessengerBundle/Resources/config/routing.yml"
    prefix:   /messenger

forum:
    resource: "@ForumBundle/Resources/config/routing.yml"
    prefix:   /forum

base:
    resource: "@baseBundle/Resources/config/routing.yml"
    prefix:   /
fos_message:
    resource: "@FOSMessageBundle/Resources/config/routing.xml"
    prefix: /messenger

app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

